### PR TITLE
chore(next): merge 7x into master

### PR DESCRIPTION
**Pull request by JacopoDaeli**
All right, we're in good shape to merge this into master.

### CODE REVIEW

**Comment by JacopoDaeli** [comment]
I've also created a branch `6x` to keep supporting older version of Warehouse.

**Comment by decompil3d** [comment]
Is there anything in particular that you explicitly want review on here? Should we perhaps get some packages onboarded to this new system before declaring it the new release for open-source purposes?

**Comment by JacopoDaeli** [comment]
@decompil3d more than a review, I want a broad approval to go ahead with merging 7x into master. That said, would also be nice to have a quick complete look at the new codebase to find possible typos (e.g, grammar misspelling etc) that we may missed in previous reviews.

We can always have some services onboarding to the new version internally before merging this into master. This PR is indeed meant to be used for discussing this type of matters. I do not think is necessary, I am pretty confident the new system is stable enough to be trust, but I am ok with waiting a few more weeks if you believe is better.

**Comment by decompil3d** [comment]
I think it's worth trying it out internally first. Perhaps publish from the 7.x branch with a prerelease tag (e.g. `7.0.0-beta.0`) and get it up and running and used for at least 1 package. Then once we have confidence that this works e2e and solves for the scenarios covered in 6.x, we can merge into master and publish `7.0.0`

**Comment by JacopoDaeli** [comment]
Will do @decompil3d . Sounds good to me.

**Pull request merged**
